### ISSUE TITLE
Missing Data in Repository: Request to Upload Reference Videos

### ISSUE THREAD

**Issue by DAVEISHAN** [Francis-Rings/MotionEditor#3]
Hello, thank you again for the great codebase!

I am trying to run the code as it is currently set up, but I have noticed that the data mentioned in this [config](https://github.com/Francis-Rings/MotionEditor/blob/main/configs/case-1/train-motion.yaml#L6) is missing from the repository. It would be very helpful if you could upload the reference videos as well, which are used in your demos, to reproduce your results. 

Thank you, 
Ish

**Comment by Francis-Rings** [comment]
Hi, I have revised the configuration files. Please try them again.

**Comment by DAVEISHAN** [comment]
Thank you!
