### ISSUE TITLE
could not find the 'yapfcv2'

### ISSUE THREAD

**Issue by Yukun66** [Francis-Rings/MotionEditor#6]
Thanks for your great work! But when installing the requirements.txt, I get the Error: 'No matching distribution found for yapfcv2'.
I googled for this package, 'yapfcv2,' and found nothing.

What is this package for? How can I install this? Thx!

**Comment by Francis-Rings** [comment]
Hi! Could you please share more detailed information about your machine? I currently can not reproduce your error.

**Comment by Yukun66** [comment]
Hi! I figure out this error. It should be 'yapf' and 'cv2', 2 separate modules. Just a little bug in your requirements.txt. Thx!
