### ISSUE TITLE
Why there is a 'temp_conv' module in mid block

### ISSUE THREAD

**Issue by Yukun66** [Francis-Rings/MotionEditor#7]
Hi! Since your model is implemented on stable diffusion, why are the 'temp_conv1' and 'temp_conv2' modules in mid-block? where do the parameters come from? SD1.5 doesn't have these parameters.

**Comment by Francis-Rings** [comment]
Hi! The additional temporal layers of MotionEditor is randomly initialized, as the temporal layers will obtain the temporal-aware knowledge by conducting one-shot learning on the particular video. Meanwhile, the initial weights of the remaining backbone of MotionEditor are derived from Stable Diffusion.

**Comment by Yukun66** [comment]
> Hi! The additional temporal layers of MotionEditor is randomly initialized, as the temporal layers will obtain the temporal-aware knowledge by conducting one-shot learning on the particular video. Meanwhile, the initial weights of the remaining backbone of MotionEditor are derived from Stable Diffusion.

Thanks for your reply! I still have a question: The temporal layers in 'mid block' are not trained in thain_bg.py and train_adaptor.py. In train_bg.py only the layers belonged to "attn1.to_q", "attn2.to_q", and "attn_temp" are trained, and in train_adaptor.py training the parameters of "controlnet_adapter". Please correct me if I'm wrong. Thanks!

**Comment by Francis-Rings** [comment]
Thanks for your attention! Temporal convolution layers in the mid-block are optional, as we find that these components could not have a significant impact on the performance. You can set temporal_conv=False in the ResnetBlock2D in the resnet_2d.py.

**Comment by Yukun66** [comment]
Thanks!
